services:
  verbalaize:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./whisper_models:/app/whisper_models
      - whisper_cache:/root/.cache/whisper  # Persist model cache
    environment:
      - VBZ_DEBUG=True
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  whisper_cache:  # Named volume for Whisper model cache
